### ISSUE TITLE
Setting query param to None breaks on reload

### ISSUE THREAD

**Issue by andrewhill157** [marimo-team/marimo#1105]
### Describe the bug

When using a selector and specifying the value in query_params, selecting the None value seems to break the app if it is refreshed after making this selection.

### Environment

I'm using `0.3.10` currently but I don't see a relevant fix since then in logs as far as I can tell. I can provide more details if is relevant.

### Code to reproduce

```
import marimo as mo

query_params = mo.query_params()

selector = mo.ui.dropdown(
    options=["1", "2", "3"],
    label="selector",
    allow_select_none=True,
    value=query_params["selector"] or None,
    on_change=lambda value: query_params.set("selector", value),
)

selector
```

Load with `<BASE_URL>/?selector=null` (which is what the URL becomes if you select the none value `--`  in the dropdown.

I get 
```
Traceback (most recent call last):
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/marimo/_runtime/cell_runner.py", line 228, in run
    return_value = execute_cell(cell, self.glbls)
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/marimo/_ast/cell.py", line 407, in execute_cell
    exec(cell.body, glbls)
  File "/var/folders/zl/d8pjcbrs3t7dhnck80rt_rjm0000gn/T/marimo_50503/__marimo__cell_Hbol_.py", line 5, in <module>
    selector = mo.ui.dropdown(
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/marimo/_plugins/ui/_impl/input.py", line 580, in __init__
    super().__init__(
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/marimo/_plugins/ui/_core/ui_element.py", line 129, in __init__
    self._initialize(*self._args)
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/marimo/_plugins/ui/_core/ui_element.py", line 208, in _initialize
    self._value = self._initial_value = self._convert_value(initial_value)
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/marimo/_plugins/ui/_impl/input.py", line 596, in _convert_value
    return self.options[value[0]]
KeyError: 'null'
```

**Comment by mscolnick** [comment]
thank you for reporting, ill fix this tomorrow

in the meantime, could you do:
```
on_change=lambda value: query_params.set("selector", value or ""),
```

**Comment by andrewhill157** [comment]
yes, definitely! thank you!

**Comment by mscolnick** [comment]
This is fixed in https://github.com/marimo-team/marimo/pull/1111 and will be included in the next release
