### ISSUE TITLE
Stopping a running cell crashes the kernel [windows]

### ISSUE THREAD

**Issue by MartinBernstorff** [marimo-team/marimo#1162]
### Describe the bug

Run a cell containing:

```python
import time
time.sleep(10)
```

And stop it while it is running. Crashes the kernel. May be related to #834. Cannot repro on Mac, likely because of Windows and/or Anaconda.

<details>

```bash
Exception in callback Distributor._on_change()
handle: <Handle Distributor._on_change()>
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\site-packages\marimo\_utils\distributor.py", line 46, in _on_change
    response = self.input_connection.recv()
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\multiprocessing\connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\multiprocessing\connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback Distributor._on_change()
handle: <Handle Distributor._on_change()>
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\site-packages\marimo\_utils\distributor.py", line 46, in _on_change
    response = self.input_connection.recv()
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\multiprocessing\connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\multiprocessing\connection.py", line 379, in _recv
    chunk = read(handle, remaining)

[...] (Comment was too long, seems the command repeats many times)

Exception in callback Distributor._on_change()
handle: <Handle Distributor._on_change()>
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\site-packages\marimo\_utils\distributor.py", line 46, in _on_change
    response = self.input_connection.recv()
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\multiprocessing\connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "E:\ProgramData\Anaconda3\envs\mbern-circular-import-debugging\lib\multiprocessing\connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

        The Python kernel died unexpectedly.
```

### Environment

```
{
  "marimo": "0.4.0",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 106 Stepping 6, GenuineIntel",
  "Python Version": "3.10.9",
  "Binaries": {
    "Browser": "111.0.5563.147",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.5.1",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.7.1",
    "black": "23.12.0"
  }
}
```

**Comment by akshayka** [comment]
Thanks for reporting. I will look at this early next week and will get to the bottom of this; I don't easy access to a Windows machine this week.

**Comment by akshayka** [comment]
@MartinBernstorff  - the latest release has a fix for this. Thanks again for reporting!
