### ISSUE TITLE
`TypeError` when rendering `bs4.element.ResultSet([])`

### ISSUE THREAD

**Issue by ForceBru** [marimo-team/marimo#1219]
### Describe the bug

I get this error from a cell containing only the expression `bs4.element.ResultSet([])`:

```
Traceback (most recent call last):
  File "/Users/forcebru/.pyenv/versions/3.12.1/lib/python3.12/site-packages/marimo/_output/formatting.py", line 124, in try_format
    mimetype, data = formatter(obj)
                     ^^^^^^^^^^^^^^
  File "/Users/forcebru/.pyenv/versions/3.12.1/lib/python3.12/site-packages/marimo/_output/formatters/structures.py", line 66, in _format_structure
    formatted_structure = format_structure(t)
                          ^^^^^^^^^^^^^^^^^^^
  File "/Users/forcebru/.pyenv/versions/3.12.1/lib/python3.12/site-packages/marimo/_output/formatters/structures.py", line 33, in format_structure
    return repacker([_leaf_formatter(v) for v in flattened])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/forcebru/.pyenv/versions/3.12.1/lib/python3.12/site-packages/marimo/_utils/flatten.py", line 212, in unflatten_with_validation
    return u(vector)
           ^^^^^^^^^
  File "/Users/forcebru/.pyenv/versions/3.12.1/lib/python3.12/site-packages/marimo/_utils/flatten.py", line 50, in <lambda>
    return [], lambda _: type(value)()
                         ^^^^^^^^^^^^^
TypeError: ResultSet.__init__() missing 1 required positional argument: 'source'
```

It looks like the error comes from within marimo itself.

### Environment

```
{
  "marimo": "0.4.3",
  "OS": "Darwin",
  "OS Version": "22.6.0",
  "Processor": "i386",
  "Python Version": "3.12.1",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.10.0",
    "black": "24.2.0"
  }
}
```

### Code to reproduce

```python
import bs4
bs4.element.ResultSet([])
```

This happened to me in practice when trying to view the output of a `soup.find_all` that returned an empty result like:

```python
bs4.BeautifulSoup().find_all(True)
```

**Comment by mscolnick** [comment]
thanks for reporting! will look into this today, and hopefully release by tomorrow at the latest
