### ISSUE TITLE
Unable to run pyodide

### ISSUE THREAD

**Issue by hieutrluu** [marimo-team/marimo#1321]
### Describe the bug

I follow the instruction
```bash
python3 pyodide/build_and_serve.py
# then in another terminal
cd frontend
PYODIDE=true pnpm dev
```

But I receive the error and screenshot
```
Traceback (most recent call last): File "/lib/python311.zip/_pyodide/_base.py", line 573, in eval_code_async await CodeRunner( File "/lib/python311.zip/_pyodide/_base.py", line 395, in run_async await coroutine File "<exec>", line 4, in <module> File "/lib/python3.11/site-packages/micropip/_commands/install.py", line 142, in install await transaction.gather_requirements(requirements) File "/lib/python3.11/site-packages/micropip/transaction.py", line 204, in gather_requirements await asyncio.gather(*requirement_promises) File "/lib/python3.11/site-packages/micropip/transaction.py", line 217, in add_requirement await self.add_wheel(wheel, extras=set(), specifier="") File "/lib/python3.11/site-packages/micropip/transaction.py", line 383, in add_wheel await wheel.download(self.fetch_kwargs) File "/lib/python3.11/site-packages/micropip/transaction.py", line 100, in download with ZipFile(data) as zip_file: ^^^^^^^^^^^^^ File "/lib/python311.zip/zipfile.py", line 1301, in __init__ self._RealGetContents() File "/lib/python311.zip/zipfile.py", line 1368, in _RealGetContents raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file
```

<img width="632" alt="Screenshot 2024-05-06 at 14 45 37" src="https://github.com/marimo-team/marimo/assets/32662977/3c1aaeae-4e22-4525-9e92-683336b7f7d3">

### Environment

{
  "marimo": "0.4.7",
  "OS": "Darwin",
  "OS Version": "23.0.0",
  "Processor": "arm",
  "Python Version": "3.12.1",
  "Binaries": {
    "Browser": "124.0.6367.119",
    "Node": "v20.11.0"
  },
  "Requirements": {
    "click": "8.1.3",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8",
    "pygments": "2.17.2",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.11.0",
    "black": "23.3.0"
  }
}

**Comment by mscolnick** [comment]
Is there anything that was output in the root level `dist` directory? Your might need to build the repo once (`python build`), or just edit any file to trigger a build while running `pyodide/build_and_serve.py`

**Comment by dmadisetti** [comment]
So I sometimes have to patch: frontend/src/core/pyodide/worker/getMarimoWheel.ts

to just return `http://localhost:8000/dist/marimo-0.x.x-py3-none-any.whl`

I figured maybe I was just doing something wrong

**Comment by mscolnick** [comment]
I am actually working on a fix for this now so these can stay in sync. Mostly just didnt invest much time in the local development mode for this.
