### ISSUE TITLE
Blog DAG code error

### ISSUE THREAD

**Issue by frhino** [marimo-team/marimo#1431]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [ ] Confusing
- [X] Not sure?

### Explain in Detail

https://marimo.io/blog/lessons-learned

In the DAG section, the two embedded marimo notebooks display an error:

## Something went wrong
```
Traceback (most recent call last): File "/lib/python312.zip/_pyodide/_base.py", line 574, in eval_code_async await CodeRunner( File "/lib/python312.zip/_pyodide/_base.py", line 396, in run_async await coroutine File "<exec>", line 2, in <module> ModuleNotFoundError: No module named 'micropip' The module 'micropip' is included in the Pyodide distribution, but it is not installed. You can install it by calling: await micropip.install("micropip") in Python, or await pyodide.loadPackage("micropip") in JavaScript See https://pyodide.org/en/stable/usage/loading-packages.html for more details.
```
###### `Try again`
---
Try again isn't working. Tried refreshing browser. 
Chrome 125.0.6422.52
Android 14; Pixel 6 Pro Build/AP1A.240505.004

### Your Suggestion for Changes

Suggest adding a footnote in case it isn't expected to work on some devices and should be viewed on desktop.

**Comment by mscolnick** [comment]
It looks like it is back - it was likely a downstream issue from Pyodide as we pull in their `dev` branch in our [marimo.app](https://marimo.app/) playground. 

We can look into moving back to stable
