### ISSUE TITLE
add `packaging` to dependencies?

### ISSUE THREAD

**Issue by baggiponte** [marimo-team/marimo#1783]
Ciao! I installed the latest marimo on a fresh env with py 3.11 using uv. When I run the notebook, I get the following error:

```bash
v run marimo new
warning: `uv run` is experimental and may change without warning.
Traceback (most recent call last):
  File "/Users/luca/dev/learn/d2l/.venv/bin/marimo", line 5, in <module>
    from marimo._cli.cli import main
  File "/Users/luca/dev/learn/d2l/.venv/lib/python3.11/site-packages/marimo/_cli/cli.py", line 17, in <module>
    from marimo._cli.development.commands import development
  File "/Users/luca/dev/learn/d2l/.venv/lib/python3.11/site-packages/marimo/_cli/development/commands.py", line 26, in <module>
    from marimo._server.api.router import build_routes
  File "/Users/luca/dev/learn/d2l/.venv/lib/python3.11/site-packages/marimo/_server/api/router.py", line 16, in <module>
    from marimo._server.api.endpoints.execution import router as execution_router
  File "/Users/luca/dev/learn/d2l/.venv/lib/python3.11/site-packages/marimo/_server/api/endpoints/execution.py", line 24, in <module>
    from marimo._server.uvicorn_utils import close_uvicorn
  File "/Users/luca/dev/learn/d2l/.venv/lib/python3.11/site-packages/marimo/_server/uvicorn_utils.py", line 8, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

**Repro**

```bash
uv venv --python=3.11 --python-preference=only-managed
uv pip install marimo
uv run marimo new
```

**Ref in the code**
https://github.com/marimo-team/marimo/blob/b0efec00d8989ce9745574227b86f8c00cce9127/marimo/_server/uvicorn_utils.py#L8

**Comment by mscolnick** [comment]
it's possible that `black` installed this and moving from `black` to `ruff`, maybe we lost this? unsure why this isnt caught in CI.

**Comment by baggiponte** [comment]
> it's possible that `black` installed this and moving from `black` to `ruff`, maybe we lost this? unsure why this isnt caught in CI.

Maybe the CI runner already has `packaging` installed? Indeed `black` has a dependency on `packaging`.
