### ISSUE TITLE
displaying a polars dataframe with an array column spews error output

### ISSUE THREAD

**Issue by ggggggggg** [marimo-team/marimo#1853]
### Describe the bug

```
import polars as pl
import numpy as np
_df = pl.DataFrame({"a":[np.arange(5) for i in range(10)]},schema={"a":pl.Array(pl.Int64,5)})
_df
```
Results in lots of red text error output. The dataframe actually is printed, but I'd prefer it without all the error output. Similar to #1706 

<details>
<summary>error ouput</summary>

```python

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\oneilg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\marimo\_plugins\ui\_impl\tables\polars_table.py", line 34, in to_csv
    return self.data.write_csv().encode("utf-8")
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneilg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\polars\dataframe\frame.py", line 2696, in write_csv
    self._df.write_csv(
polars.exceptions.ComputeError: datatype array[i64, 5] cannot be written to csv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\oneilg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\marimo\_output\formatters\df_formatters.py", line 27, in _show_marimo_dataframe
    return table(df, selection=None, pagination=True)._mime_()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneilg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\marimo\_plugins\ui\_impl\table.py", line 227, in __init__
    "data": self._filtered_manager.to_data(),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneilg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\marimo\_plugins\ui\_impl\tables\table_manager.py", line 32, in to_data
    return mo_data.csv(self.to_csv()).url
                       ^^^^^^^^^^^^^
  File "C:\Users\oneilg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\marimo\_plugins\ui\_impl\tables\polars_table.py", line 50, in to_csv
    column.cast(pl.Array(pl.Utf8)).arr.join(",")
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\oneilg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\polars\datatypes\classes.py", line 676, in __init__
    raise TypeError(msg)
TypeError: Array constructor is missing the required argument `shape`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
OSError: [WinError 1] Incorrect function
Call stack:
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\oneilg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\marimo\_runtime\runtime.py", line 1762, in launch_kernel
    asyncio.run(control_loop())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
```
</details>

### Environment

{
  "marimo": "0.7.9",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 142 Stepping 10, GenuineIntel",
  "Python Version": "3.12.4",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.13.0",
    "uvicorn": "0.30.3",
    "starlette": "0.38.0",
    "websockets": "12.0",
    "typing-extensions": "4.12.2",
    "ruff": "0.5.4"
  }
}

**Comment by mscolnick** [comment]
What polars version are you on? Can you try upgrading?

**Comment by ggggggggg** [comment]
This is with polars 1.2.1, which is the current release.

**Comment by mscolnick** [comment]
Ah thank you, I was able to reproduce, I have a fix up now https://github.com/marimo-team/marimo/pull/1854
