### ISSUE TITLE
intermittent errors with mo.mpl.interactive(plt.gcf())

### ISSUE THREAD

**Issue by ggggggggg** [marimo-team/marimo#1860]
### Describe the bug

When reloading a large (50 cells, 30 second total execution time) notebook, I often find cells that have error output. When I re-run the cells, they work fine. An example of the error output is pasted below

```python
A0>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\marimo\_plugins\stateless\mpl\_mpl.py", line 158, in send
    await websocket.close()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\starlette\websockets.py", line 203, in close
    await self.send(
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\starlette\websockets.py", line 112, in send
    raise RuntimeError('Cannot call "send" once a close message has been sent.')
RuntimeError: Cannot call "send" once a close message has been sent.
Exception ignored in: <coroutine object create_application.<locals>.websocket_endpoint.<locals>.send at 0x000002058F1F46D0>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\marimo\_plugins\stateless\mpl\_mpl.py", line 158, in send
    await websocket.close()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\starlette\websockets.py", line 203, in close
    await self.send(
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\starlette\websockets.py", line 112, in send
    raise RuntimeError('Cannot call "send" once a close message has been sent.')
RuntimeError: Cannot call "send" once a close message has been sent.
```

### Environment

{
  "marimo": "0.7.9",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 142 Stepping 10, GenuineIntel",
  "Python Version": "3.12.4",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.13.0",
    "uvicorn": "0.30.3",
    "starlette": "0.38.0",
    "websockets": "12.0",
    "typing-extensions": "4.12.2",
    "ruff": "0.5.4"
  }
}
also possibly relevant:
matplotlib         3.9.1
matplotlib-inline  0.1.7

### Code to reproduce

I haven't been able to reduce this to a reproducible example. My best guess is that it can happen in any cell that ends with `mo.mpl.interactive(plt.gcf())` and has something to do with timing and whether is on screen of off screen at certain times.

**Comment by mscolnick** [comment]
It may be that `mo.mpl.interactive(plt.gcf())` is re-rendering and the connection is closed while the backend is sending _something_. This is often a race-condition that can actually be ignored/caught.

**Comment by ggggggggg** [comment]
Most if not all of the time the plot has appeared and the ui on the plot for zooming is responsive, even when this error appears. Also this error does not increase the error counter in the lower left. 

I'm pretty sure I saw it once on a cell without `mo.mpl.interactive(plt.gcf())` but I haven't been able to reproduce it.

**Comment by mscolnick** [comment]
Yea - I think it is just _noise_ in that case. We basically try to close and already closed websocket. I added a check here: https://github.com/marimo-team/marimo/pull/1861
