### ISSUE TITLE
Possible incompatibility when using marimo_csv transformer with altair 5.4.0

### ISSUE THREAD

**Issue by andrewhill157** [marimo-team/marimo#2005]
### Describe the bug

When generating a plot using the marimo_csv transformer, I'm getting a DataFrame constructor not properly called error.

This seems to be linked to an upgrade from altair `5.3.0` to `5.4.0` on my end, but only happens with the marimo csv transformer as far as I can tell.

```
Traceback (most recent call last):
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/marimo/_output/formatting.py", line 172, in try_format
    mimetype, data = formatter(obj)
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/marimo/_output/formatters/altair_formatters.py", line 44, in _show_chart
    srcdoc=html.escape(chart.to_html()),
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 1946, in to_html
    self.to_dict(),
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 3772, in to_dict
    return super().to_dict(**kwds)
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 1798, in to_dict
    copy.data = _prepare_data(data, context)
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 275, in _prepare_data
    data = func(data)
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/marimo/_plugins/ui/_impl/charts/altair_transformer.py", line 56, in _to_marimo_csv
    data_csv = _data_to_csv_string(data)
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/marimo/_plugins/ui/_impl/charts/altair_transformer.py", line 99, in _data_to_csv_string
    return get_table_manager(data).to_csv().decode("utf-8")
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/marimo/_plugins/ui/_impl/tables/default_table.py", line 89, in to_csv
    return self._as_table_manager().to_csv(format_mapping)
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/marimo/_plugins/ui/_impl/tables/default_table.py", line 161, in _as_table_manager
    return PandasTableManagerFactory.create()(pd.DataFrame(self.data))
  File "/Users/andrewhill/Desktop/absel/env/lib/python3.10/site-packages/pandas/core/frame.py", line 886, in __init__
    raise ValueError("DataFrame constructor not properly called!")
ValueError: DataFrame constructor not properly called!
```

### Environment

```
{
  "marimo": "0.7.19",
  "OS": "Darwin",
  "OS Version": "23.5.0",
  "Processor": "arm",
  "Python Version": "3.10.4",
  "Binaries": {
    "Browser": "--",
    "Node": "v21.7.1"
  },
  "Requirements": {
    "click": "8.1.3",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.11.0",
    "ruff": "0.3.7"
  }
}
```

### Code to reproduce

```
@app.cell
def __():
    import marimo as mo
    import polars as pl
    import altair as alt

   # if remove this line and restart kernel, plot appears as expected
    alt.data_transformers.enable("marimo_csv")

    test_data = pl.DataFrame({
        "name": ["Alice", "Bob", "Charlie", "David"],
        "salary": [50000, 60000, 75000, 55000],
    })


    (
        alt.Chart(test_data.to_pandas())
        .encode(
            y="salary",
            x="name",
        )
        .mark_point(color="red")
    )

    return alt, mo, pl, test_data


if __name__ == "__main__":
    app.run()
```

**Comment by mscolnick** [comment]
It looks like altair moved to https://github.com/narwhals-dev/narwhals which has broken the `data_transformers` API. I can fix this in our repo, but I would consider this a breaking change from them.

**Comment by mscolnick** [comment]
I have a fix for this: https://github.com/marimo-team/marimo/pull/2006
Thanks for flagging.
