### ISSUE TITLE
package manager - switch default

### ISSUE THREAD

**Issue by shuther** [marimo-team/marimo#2425]
### Describe the bug

I tried to install a package and marimo proposed me different methods. I tried pixi while pixi is not installed - I am using pipx for now.
Now, when I go to the Manage packages section in marimo, I have the log below on the server side.

Expectation:
1- I would like to reset the package manager, maybe a documentation about it so users know to edit  ~/.marimo.toml
2- maybe if pixi is not installed or present, we can avoid the traceback below and pixi should not be added? 

```
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/_utils.py", line 77, in collapse_excgroups
  |     yield
  |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/base.py", line 186, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    |     return await self.app(scope, receive, send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/marimo/_server/api/auth.py", line 216, in __call__
    |     return await super().__call__(scope, receive, send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    |     await self.app(scope, receive, send_wrapper)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/base.py", line 185, in __call__
    |     with collapse_excgroups():
    |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    |     raise exc
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/marimo/_server/api/middleware.py", line 129, in dispatch
    |     return await call_next(request)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/authentication.py", line 48, in __call__
    |     await self.app(scope, receive, send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    |     await self.app(scope, receive, send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/marimo/_server/api/middleware.py", line 79, in __call__
    |     return await self.app(scope, receive, send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    |     raise exc
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 460, in handle
    |     await self.app(scope, receive, send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    |     raise exc
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    |     response = await f(request)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/marimo/_server/router.py", line 102, in wrapper_func
    |     response = await response
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/authentication.py", line 75, in async_wrapper
    |     return await func(*args, **kwargs)
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/marimo/_server/api/endpoints/packages.py", line 119, in list_packages
    |     packages = package_manager.list_packages()
    |   File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/marimo/_runtime/packages/conda_package_manager.py", line 34, in list_packages
    |     proc = subprocess.run(
    |   File "/usr/lib/python3.10/subprocess.py", line 503, in run
    |     with Popen(*popenargs, **kwargs) as process:
    |   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    |     self._execute_child(args, executable, preexec_fn, close_fds,
    |   File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    |     raise child_exception_type(errno_num, err_msg, err_filename)
    | FileNotFoundError: [Errno 2] No such file or directory: 'pixi'
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/marimo/_server/api/auth.py", line 216, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    raise exc
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/marimo/_server/api/middleware.py", line 129, in dispatch
    return await call_next(request)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/authentication.py", line 48, in __call__
    await self.app(scope, receive, send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/marimo/_server/api/middleware.py", line 79, in __call__
    return await self.app(scope, receive, send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 460, in handle
    await self.app(scope, receive, send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/marimo/_server/router.py", line 102, in wrapper_func
    response = await response
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/starlette/authentication.py", line 75, in async_wrapper
    return await func(*args, **kwargs)
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/marimo/_server/api/endpoints/packages.py", line 119, in list_packages
    packages = package_manager.list_packages()
  File "/home/shuther/.local/pipx/venvs/marimo/lib/python3.10/site-packages/marimo/_runtime/packages/conda_package_manager.py", line 34, in list_packages
    proc = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pixi' 
```

### Environment

{
  "marimo": "0.8.20",
  "OS": "Linux",
  "OS Version": "6.10.10-zabbly+",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Browser": "129.0.6668.58",
    "Node": "v22.9.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "6.4.4",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.9",
    "ruff": "0.6.4",
    "starlette": "0.38.5",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.4.1",
    "anywidget": "0.9.13",
    "duckdb": "1.0.0",
    "pandas": "2.2.2",
    "polars": "1.6.0",
    "pyarrow": "17.0.0"
  }
}

### Code to reproduce

n/a

**Comment by mscolnick** [comment]
@shuther - you can switch your package manager in the settings modal

<img width="1387" alt="image" src="https://github.com/user-attachments/assets/05e57c7c-7cbb-494f-9ecf-9e3b1be076df">


I am also going to fix the warnings / error messages to be more helpful.
