### ISSUE TITLE
marimo convert Jupyter notebook to Marimo notebook shouldn't rely on > which is OS dependant

### ISSUE THREAD

**Issue by scls19fr** [marimo-team/marimo#2460]
### Describe the bug

Hello,

I have some Jupyter notebooks with some accentuated characters.

Under Windows 11 / Anaconda Prompt (or Anaconda Powershell Prompt)

    > marimo convert 2_correction_inertie.ipynb > 2_correction_inertie.py

    > marimo edit 2_correction_inertie.py
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "C:\tools\Anaconda3\Scripts\marimo.exe\__main__.py", line 7, in <module>
      File "C:\tools\Anaconda3\Lib\site-packages\click\core.py", line 1157, in __call__
        return self.main(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\tools\Anaconda3\Lib\site-packages\click\core.py", line 1078, in main
        rv = self.invoke(ctx)
             ^^^^^^^^^^^^^^^^
      File "C:\tools\Anaconda3\Lib\site-packages\click\core.py", line 1688, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\tools\Anaconda3\Lib\site-packages\click\core.py", line 1434, in invoke
        return ctx.invoke(self.callback, **ctx.params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\tools\Anaconda3\Lib\site-packages\click\core.py", line 783, in invoke
        return __callback(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\tools\Anaconda3\Lib\site-packages\marimo\_cli\cli.py", line 324, in edit
        codegen.get_app(name)
      File "C:\tools\Anaconda3\Lib\site-packages\marimo\_ast\codegen.py", line 214, in get_app
        contents = f.read().strip()
                   ^^^^^^^^
      File "<frozen codecs>", line 322, in decode
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 443: invalid continuation byte

My opinion is that converting (as exporting) shouldn't rely on > which is OS dependant.

Having a --output parameter (as marimo export) should help to fix that.

Kind regards

### Environment

    {
      "marimo": "0.8.22",
      "OS": "Windows",
      "OS Version": "11",
      "Processor": "Intel64 Family 6 Model 183 Stepping 1, GenuineIntel",
      "Python Version": "3.11.7",
      "Binaries": {
        "Browser": "128.0.6613.138",
        "Node": "v22.4.0"
      },
      "Dependencies": {
        "click": "8.1.7",
        "importlib-resources": "missing",
        "jedi": "0.18.1",
        "markdown": "3.6",
        "pygments": "2.15.1",
        "pymdown-extensions": "10.8.1",
        "ruff": "0.3.5",
        "starlette": "0.37.2",
        "tomlkit": "0.12.5",
        "typing-extensions": "4.9.0",
        "uvicorn": "0.30.1",
        "websockets": "12.0"
      },
      "Optional Dependencies": {
        "altair": "5.0.1",
        "pandas": "2.1.4",
        "pyarrow": "14.0.2"
      }
    }

### Code to reproduce

```
{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "cd9224ec-559e-4efd-b30e-acd035a21807",
   "metadata": {},
   "source": [
    "# Mécanisme hélicoïdal"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a3fbe82a-ef31-473b-a820-0d1be1de4436",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "hello\n"
     ]
    }
   ],
   "source": [
    "print(\"hello\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3eca9cd3-f09b-4a37-843a-4ffa1aecf9d1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

**Comment by scls19fr** [comment]
See generated marimo notebook

![image](https://github.com/user-attachments/assets/d831bdea-4339-4b6e-bf3c-7d6678ff6c48)

MÚcanisme hÚlico´dal

instead of

Mécanisme hélicoïdal

**Comment by scls19fr** [comment]
Thanks @mscolnick
