### ISSUE TITLE
Selection in layered altair plots causes an exception

### ISSUE THREAD

**Issue by poke1024** [marimo-team/marimo#2737]
### Describe the bug

Selecting data in a layered altair chart causes an exception:

```
An exception was raised by a UIElement's on_change handler:

Traceback (most recent call last):
  File "/Users/ch/miniconda3/envs/marimo/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 175, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index_class_helper.pxi", line 70, in pandas._libs.index.Int64Engine._check_type
KeyError: np.True_

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ch/miniconda3/envs/marimo/lib/python3.12/site-packages/marimo/_runtime/runtime.py", line 1473, in set_ui_element_value
    component._update(value)
  File "/Users/ch/miniconda3/envs/marimo/lib/python3.12/site-packages/marimo/_plugins/ui/_core/ui_element.py", line 449, in _update
    self._value = self._convert_value(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ch/miniconda3/envs/marimo/lib/python3.12/site-packages/marimo/_plugins/ui/_impl/altair_chart.py", line 416, in _convert_value
    return _filter_dataframe(self.dataframe, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ch/miniconda3/envs/marimo/lib/python3.12/site-packages/marimo/_plugins/ui/_impl/altair_chart.py", line 129, in _filter_dataframe
    df = df.filter(
         ^^^^^^^^^^
  File "/Users/ch/miniconda3/envs/marimo/lib/python3.12/site-packages/narwhals/dataframe.py", line 1868, in filter
    return super().filter(*predicates)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ch/miniconda3/envs/marimo/lib/python3.12/site-packages/narwhals/dataframe.py", line 166, in filter
    self._compliant_frame.filter(*predicates),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ch/miniconda3/envs/marimo/lib/python3.12/site-packages/narwhals/_pandas_like/dataframe.py", line 349, in filter
    return self._from_native_frame(self._native_frame.loc[_mask])
                                   ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/ch/miniconda3/envs/marimo/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ch/miniconda3/envs/marimo/lib/python3.12/site-packages/pandas/core/indexing.py", line 1431, in _getitem_axis
    return self._get_label(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ch/miniconda3/envs/marimo/lib/python3.12/site-packages/pandas/core/indexing.py", line 1381, in _get_label
    return self.obj.xs(label, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ch/miniconda3/envs/marimo/lib/python3.12/site-packages/pandas/core/generic.py", line 4301, in xs
    loc = index.get_loc(key)
          ^^^^^^^^^^^^^^^^^^
  File "/Users/ch/miniconda3/envs/marimo/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: np.True_
[Search on Google](https://www.google.com/search?q=KeyError%3A%20np.True_)
```

### Environment

{
  "marimo": "0.9.14",
  "OS": "Darwin",
  "OS Version": "24.0.0",
  "Processor": "arm",
  "Python Version": "3.12.2",
  "Binaries": {
    "Browser": "130.0.6723.70",
    "Node": "v22.4.1"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.20.1",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "narwhals": "1.9.3",
    "packaging": "24.0",
    "psutil": "6.0.0",
    "pygments": "2.17.2",
    "pymdown-extensions": "10.7.1",
    "pyyaml": "6.0.1",
    "ruff": "0.6.9",
    "starlette": "0.37.2",
    "tomlkit": "0.12.4",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.29.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.4.1",
    "pandas": "2.2.3",
    "pyarrow": "18.0.0"
  }
}

### Code to reproduce

import marimo as mo
import altair as alt
import pandas as pd

base = alt.Chart(pd.DataFrame({'x': [1, 2, 3], 'y': [2, 4, 9]}))
chart = alt.layer(base.mark_line().encode(x='x', y='y'), base.mark_circle().encode(x='x', y='y'))
mo.ui.altair_chart(chart)

**Comment by mscolnick** [comment]
Thanks for filing this. I am trying to reproduce this, but I cannot with your example. Can you verify once more your example does product this error? Maybe in a new venv?

**Comment by poke1024** [comment]
@mscolnick Hm, a fresh install (`conda create -n marimo_fresh python=3.12`) fixes this for me as well. Will reopen in case I can reproduce.
