### ISSUE TITLE
Online playground not working

### ISSUE THREAD

**Issue by damienrj** [marimo-team/marimo#2900]
### Describe the bug

I try to open the online playground and get the error:
```
Traceback (most recent call last): File "/lib/python312.zip/_pyodide/_base.py", line 522, in eval_code .run(globals, locals) ^^^^^^^^^^^^^^^^^^^^ File "/lib/python312.zip/_pyodide/_base.py", line 356, in run coroutine = eval(self.code, globals, locals) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<exec>", line 5, in <module> File "/lib/python3.12/site-packages/marimo/__init__.py", line 86, in <module> import marimo._islands as islands File "/lib/python3.12/site-packages/marimo/_islands/__init__.py", line 9, in <module> from marimo._islands.island_generator import ( File "/lib/python3.12/site-packages/marimo/_islands/island_generator.py", line 13, in <module> from marimo._output.formatting import as_html, mime_to_html File "/lib/python3.12/site-packages/marimo/_output/formatting.py", line 35, in <module> from marimo._plugins.stateless.json_output import json_output File "/lib/python3.12/site-packages/marimo/_plugins/stateless/json_output.py", line 7, in <module> from marimo._plugins.core.web_component import JSONType, build_stateless_plugin File "/lib/python3.12/site-packages/marimo/_plugins/core/web_component.py", line 26, in <module> from marimo._output.md import _md File "/lib/python3.12/site-packages/marimo/_output/md.py", line 7, in <module> import markdown # type: ignore ^^^^^^^^^^^^^^^ ModuleNotFoundError: No module named 'markdown' The module 'markdown' is included in the Pyodide distribution, but it is not installed. You can install it by calling: await micropip.install("markdown") in Python, or await pyodide.loadPackage("markdown") in JavaScript See https://pyodide.org/en/stable/usage/loading-packages.html for more details.
```

### Environment

https://marimo.app/l/c7h6pz

**Comment by mscolnick** [comment]
@damienrj - I cannot reproduce this error. Can you share what browser you are using? can you try other browsers?

**Comment by mscolnick** [comment]
It sounds like your VPN is avoiding downloading some required files. I am not sure if that is all VPNs, though.

**Comment by damienrj** [comment]
Yeah, makes sense. I think the error message improvement would be less VPN specific and more along the lines of it can't download packages which is what I think was happening in my case. But not a large issue.
Thanks
