### ISSUE TITLE
create_asgi_app: very unstable with multiple uvicorn workers

### ISSUE THREAD

**Issue by liquidcarbon** [marimo-team/marimo#2953]
I've been experimenting with dashboards composed of very minimal marimo apps.  Thus far I ran them as a single uvicorn worker; this time I tried multiple workers, via either gunicorn or uvicorn.  The apps never load on first try, and always crash on refresh.  It's pretty much unusable this way.

Code to reproduce below.  It took 3-4 refreshes to see "hi"; refreshing crashes it again.

```python
# motest.py
import marimo

__generated_with = "0.9.21"
app = marimo.App(width="full")


@app.cell
def __():
    import marimo as mo
    mo.md("hi")
    return (mo,)


if __name__ == "__main__":
    app.run()
```

```python
# tmo/app.py
from fastapi import FastAPI
from marimo import create_asgi_app
from pathlib import Path

# Create a marimo asgi app
marimo_file = Path(__file__).parent / "motest.py"
if marimo_file.exists():
    server = create_asgi_app().with_app(path="/motest", root=marimo_file.as_posix())
else:
    exit()

# Create a FastAPI app
app = FastAPI()
app.mount("/", server.build())
```

```
.venv/bin/uvicorn app:app --host 0.0.0.0 --port 8001 --workers 2
INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
INFO:     Started parent process [3592974]
INFO:     Started server process [3592977]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [3592976]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     10.125.136.74:63254 - "GET /motest HTTP/1.1" 301 Moved Permanently
INFO:     10.125.136.74:63254 - "GET /motest/ HTTP/1.1" 200 OK
INFO:     10.125.136.74:63254 - "GET /motest/assets/gradient-yHQUC_QB.png HTTP/1.1" 200 OK
INFO:     10.125.136.74:63258 - "GET /motest/assets/PTSans-Bold-D9fedIX3.ttf HTTP/1.1" 200 OK
INFO:     10.125.136.74:63257 - "GET /motest/assets/index-CwO3Nrt7.css HTTP/1.1" 200 OK
INFO:     10.125.136.74:63259 - "GET /motest/assets/PTSans-Regular-CxL0S8W7.ttf HTTP/1.1" 200 OK
INFO:     10.125.136.74:63260 - "GET /motest/assets/FiraMono-Regular-BTCkDNvf.ttf HTTP/1.1" 200 OK
INFO:     10.125.136.74:63261 - "GET /motest/assets/Lora-VariableFont_wght-B2ootaw-.ttf HTTP/1.1" 200 OK
INFO:     10.125.136.74:63254 - "GET /motest/assets/FiraMono-Medium-DU3aDxX5.ttf HTTP/1.1" 200 OK
INFO:     10.125.136.74:63260 - "GET /motest/assets/FiraMono-Bold-CLVRCuM9.ttf HTTP/1.1" 200 OK
INFO:     10.125.136.74:63261 - "GET /motest/assets/index-6Zvy9-Zv.js HTTP/1.1" 200 OK
INFO:     10.125.136.74:63258 - "GET /motest/assets/noise-60BoTA8O.png HTTP/1.1" 200 OK
INFO:     10.125.136.74:63254 - "GET /motest/assets/useMarimoWebSocket-BZh7ReXE.js HTTP/1.1" 200 OK
INFO:     10.125.136.74:63260 - "GET /motest/assets/useMarimoWebSocket-D4wG0iNK.css HTTP/1.1" 200 OK
INFO:     10.125.136.74:63261 - "GET /motest/assets/run-page-B-B2HuzH.js HTTP/1.1" 200 OK
INFO:     10.125.136.74:63258 - "GET /motest/assets/web-vitals-DSwKt_Ty.js HTTP/1.1" 200 OK
INFO:     10.125.136.74:63260 - "GET /motest/favicon.ico HTTP/1.1" 200 OK
INFO:     ('10.125.136.74', 63263) - "WebSocket /motest/ws?session_id=s_cvsbpz" [accepted]
INFO:     connection open
INFO:     10.125.136.74:63260 - "POST /motest/api/kernel/instantiate HTTP/1.1" 401 Unauthorized
INFO:     connection closed
INFO:     10.125.136.74:63265 - "GET /motest/ HTTP/1.1" 200 OK
INFO:     ('10.125.136.74', 63267) - "WebSocket /motest/ws?session_id=s_azp0ai" [accepted]
INFO:     connection open
[W 241125 07:36:27 deps:131] Valid sessions: []
INFO:     10.125.136.74:63265 - "POST /motest/api/kernel/instantiate HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 76, in collapse_excgroups
  |     yield
  |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 186, in __call__
  |     async with anyio.create_task_group() as task_group:
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/data/code/momount/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 460, in handle
    |     await self.app(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 460, in handle
    |     await self.app(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    |     with collapse_excgroups():
    |          ^^^^^^^^^^^^^^^^^^^^
    |   File "/data/code/.pixi/envs/default/lib/python3.12/contextlib.py", line 158, in __exit__
    |     self.gen.throw(value)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/marimo/_server/api/middleware.py", line 145, in dispatch
    |     return await call_next(request)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/authentication.py", line 48, in __call__
    |     await self.app(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__
    |     await self.simple_response(scope, receive, send, request_headers=headers)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    |     await self.app(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/marimo/_server/api/middleware.py", line 117, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/marimo/_server/api/middleware.py", line 338, in __call__
    |     await self.app(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 460, in handle
    |     await self.app(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    |     response = await f(request)
    |                ^^^^^^^^^^^^^^^^
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/marimo/_server/router.py", line 54, in wrapper_func
    |     response = await func(request=request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/marimo/_server/api/endpoints/execution.py", line 92, in instantiate
    |     app_state.require_current_session().instantiate(body)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/data/code/momount/.venv/lib/python3.12/site-packages/marimo/_server/api/deps.py", line 135, in require_current_session
    |     raise ValueError(f"Invalid session id: {session_id}")
    | ValueError: Invalid session id: s_azp0ai
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/code/momount/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/code/momount/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/code/momount/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 460, in handle
    await self.app(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 460, in handle
    await self.app(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
         ^^^^^^^^^^^^^^^^^^^^
  File "/data/code/.pixi/envs/default/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/code/momount/.venv/lib/python3.12/site-packages/marimo/_server/api/middleware.py", line 145, in dispatch
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/authentication.py", line 48, in __call__
    await self.app(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/marimo/_server/api/middleware.py", line 117, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/code/momount/.venv/lib/python3.12/site-packages/marimo/_server/api/middleware.py", line 338, in __call__
    await self.app(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 460, in handle
    await self.app(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/data/code/momount/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/data/code/momount/.venv/lib/python3.12/site-packages/marimo/_server/router.py", line 54, in wrapper_func
    response = await func(request=request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/code/momount/.venv/lib/python3.12/site-packages/marimo/_server/api/endpoints/execution.py", line 92, in instantiate
    app_state.require_current_session().instantiate(body)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/code/momount/.venv/lib/python3.12/site-packages/marimo/_server/api/deps.py", line 135, in require_current_session
    raise ValueError(f"Invalid session id: {session_id}")
ValueError: Invalid session id: s_azp0ai
INFO:     connection closed
INFO:     ('10.125.136.74', 63273) - "WebSocket /motest/ws?session_id=s_azp0ai" [accepted]
INFO:     connection open
INFO:     10.125.136.74:63278 - "GET /motest/ HTTP/1.1" 200 OK
INFO:     connection closed
INFO:     10.125.136.74:63278 - "GET /motest/assets/gradient-yHQUC_QB.png HTTP/1.1" 304 Not Modified
INFO:     10.125.136.74:63283 - "GET /motest/assets/PTSans-Regular-CxL0S8W7.ttf HTTP/1.1" 304 Not Modified
INFO:     10.125.136.74:63279 - "GET /motest/assets/index-CwO3Nrt7.css HTTP/1.1" 304 Not Modified
INFO:     10.125.136.74:63280 - "GET /motest/assets/PTSans-Bold-D9fedIX3.ttf HTTP/1.1" 304 Not Modified
INFO:     10.125.136.74:63282 - "GET /motest/assets/FiraMono-Regular-BTCkDNvf.ttf HTTP/1.1" 304 Not Modified
INFO:     10.125.136.74:63281 - "GET /motest/assets/Lora-VariableFont_wght-B2ootaw-.ttf HTTP/1.1" 304 Not Modified
INFO:     10.125.136.74:63278 - "GET /motest/assets/FiraMono-Medium-DU3aDxX5.ttf HTTP/1.1" 304 Not Modified
INFO:     10.125.136.74:63279 - "GET /motest/assets/FiraMono-Bold-CLVRCuM9.ttf HTTP/1.1" 304 Not Modified
INFO:     10.125.136.74:63280 - "GET /motest/assets/index-6Zvy9-Zv.js HTTP/1.1" 304 Not Modified
INFO:     10.125.136.74:63282 - "GET /motest/assets/noise-60BoTA8O.png HTTP/1.1" 304 Not Modified
INFO:     10.125.136.74:63282 - "GET /motest/assets/run-page-B-B2HuzH.js HTTP/1.1" 304 Not Modified
INFO:     10.125.136.74:63279 - "GET /motest/assets/useMarimoWebSocket-D4wG0iNK.css HTTP/1.1" 304 Not Modified
INFO:     10.125.136.74:63280 - "GET /motest/assets/useMarimoWebSocket-BZh7ReXE.js HTTP/1.1" 304 Not Modified
INFO:     10.125.136.74:63278 - "GET /motest/assets/web-vitals-DSwKt_Ty.js HTTP/1.1" 304 Not Modified
INFO:     10.125.136.74:63278 - "GET /motest/favicon.ico HTTP/1.1" 200 OK
INFO:     ('10.125.136.74', 63284) - "WebSocket /motest/ws?session_id=s_oqet47" [accepted]
INFO:     connection open
INFO:     10.125.136.74:63280 - "POST /motest/api/kernel/instantiate HTTP/1.1" 401 Unauthorized
INFO:     connection closed
```

**Comment by mscolnick** [comment]
Do unicorn workers work with stateful applications? My guess is that is spins up multiple servers which different app state (in which case I would guess it is not). marimo is stateful, so it would not work with that flag.

**Comment by liquidcarbon** [comment]
All sensible questions.  Being able to host an app with more than one worker seems like a useful, needed feature for production-grade apps.  I believe it should be feasible to confine sessions to one worker, but at this point I wouldn't know where to begin.

I think it comes down to how these matters rank on your to-do list.  As you can tell, I'm very interested in making it work :)  This is quite a bit outside my comfort zone, but I'm willing to dig in and put in the work beyond raising issues; it would help if we could pair up on a call and start with a primer on how server-side of marimo works.  Would you be interested in that?

**Comment by mscolnick** [comment]
It is not an easy change to make marimo stateless, and in-fact not possible in all scenarios. We recommend to scale vertically instead. Why are you needing to use workers? Were you hitting limitations without it?

> [uvicorn workers]...needed feature for production-grade apps

Agreed, but hopefully you are using some containerization platform for production, in which FastAPI recommends against this and instead recommends using one worker per container: "[In particular, when running on Kubernetes you will probably not want to use workers and instead run a single Uvicorn process per container,](https://fastapi.tiangolo.com/deployment/server-workers)". You don't need to use k8s but ideally you are deploying marimo in some containerized fashion. However, we also currently do not support scaling marimo apps horizontally for the same reason (it is stateful). There are easier ways around this using Sticky Session or Session Affinity, which we don't provide out of the box but are features in most cloud platforms. But uvicorn workers don't have a concept of session affinity, so I would recommend against using them.

**Comment by liquidcarbon** [comment]
Good point re production.

I'm ok with one worker for current needs - as long as multiple users can come to the same endpoint at the same time, which seems to be holding up.

**Comment by mscolnick** [comment]
Sounds good, let us know if you do hit limitations on one worker, we'd like to improve that if you do hit issue scaling.
