### ISSUE TITLE
Cannot select a bar with datetime on a bar graph

### ISSUE THREAD

**Issue by jakub-mikians-airspace-intelligence** [marimo-team/marimo#3100]
### Describe the bug

Hi,

First, let me applaud your awesome work! marimo really changed the way I approach interactive work with python and data.

I encountered a bug, I think it's a regression (I am _almost_ sure I had it working some weeks ago). In particular, I cannot select a bar in a bar chart. It can be reproduced with the following notebook (1 cell):

```py
import marimo as mo
import pandas as pd
import altair as alt
from datetime import datetime, timezone, timedelta

df = pd.DataFrame([{"datetime": datetime.fromtimestamp(i, timezone.utc), "i": i, "modulo": i%10}  for i in range(1000)])

bars = alt.Chart(df).mark_bar().encode(x="datetime:T", y="sum(modulo):Q", color="modulo:Q")
mo.ui.altair_chart(bars)
```

When you select a bar on the chart, you will see the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/marimo/_runtime/runtime.py", line 1498, in set_ui_element_value
    component._update(value)
  File "/usr/local/lib/python3.11/site-packages/marimo/_plugins/ui/_core/ui_element.py", line 457, in _update
    self._value = self._convert_value(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marimo/_plugins/ui/_impl/altair_chart.py", line 442, in _convert_value
    return _filter_dataframe(self.dataframe, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marimo/_plugins/ui/_impl/altair_chart.py", line 120, in _filter_dataframe
    resolved_values = _resolve_values(values, dtype)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marimo/_plugins/ui/_impl/altair_chart.py", line 159, in _resolve_values
    return [_coerce_value(v, dtype) for v in values]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marimo/_plugins/ui/_impl/altair_chart.py", line 159, in <listcomp>
    return [_coerce_value(v, dtype) for v in values]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marimo/_plugins/ui/_impl/altair_chart.py", line 155, in _coerce_value
    return datetime.datetime.fromtimestamp(value / 1000)
                                           ~~~~~~^~~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

![Image](https://github.com/user-attachments/assets/ea23efdb-f770-41fd-9302-709fa3bf5e8a)

### Environment

```json
{
  "marimo": "0.9.33",
  "OS": "Linux",
  "OS Version": "6.10.4-linuxkit",
  "Processor": "",
  "Python Version": "3.11.11",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.14.2",
    "packaging": "24.1",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "ruff": "0.8.0",
    "starlette": "0.41.3",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.32.1",
    "websockets": "14.1"
  },
  "Optional Dependencies": {
    "altair": "5.5.0",
    "pandas": "2.2.3",
    "pyarrow": "18.0.0"
  }
}
```

**Comment by mscolnick** [comment]
thanks for the kind words! and the repro. 

i will look into this today

**Comment by jakub-mikians-airspace-intelligence** [comment]
Hey, thanks for absolutely rapid response! Saved my day, cheers!
