### ISSUE TITLE
Improved error messages in the terminal

### ISSUE THREAD

**Issue by mscolnick** [marimo-team/marimo#3111]
### Description

Can we improve all the error messages that get printed to the terminal. E.g

- Bad parameters in the CLI or incorrect usage
- Missing files
- Missing deps (formatting, docker, package management)
- General stack traces

### Suggested solution

- More call to actions when missing dependencies (`uv` or `docker` or `ruff`).
- Colorize stack traces if possible / enabled
- Remove marimo internal from traces for known exceptions

**Comment by dmadisetti** [comment]
WRT notebooks or scripts?

Scripts are:
```text
Traceback (most recent call last):
  File "/Users/dylan/src/marimo/tests/_runtime/script_data/script_exception_with_imported_function.py", line 16, in <module>
    app.run()
  File "/nix/store/bqrip1rnlkwiwjzg9mpi1c3zm9c7iyiz-python3-3.12.10-env/lib/python3.12/site-packages/marimo/_ast/app.py", line 573, in run
    ).run()
      ^^^^^
  File "/nix/store/bqrip1rnlkwiwjzg9mpi1c3zm9c7iyiz-python3-3.12.10-env/lib/python3.12/site-packages/marimo/_runtime/app/script_runner.py", line 222, in run
    raise e.__cause__ from None  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bqrip1rnlkwiwjzg9mpi1c3zm9c7iyiz-python3-3.12.10-env/lib/python3.12/site-packages/marimo/_runtime/executor.py", line 122, in execute_cell
    exec(cell.body, glbls)
  File "/Users/dylan/src/marimo/tests/_runtime/script_data/script_exception_with_imported_function.py", line 11, in <module>
    x, y = func.divide_by_zero(10)
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dylan/src/marimo/tests/_runtime/script_data/func.py", line 3, in divide_by_zero
    y = y / x
        ~~^~~
ZeroDivisionError: division by zero
```

As of 0.13.8-dev

I don't think this is exceptionally noisy, what would be the ideal here?

---

We've also had some iteration with notebooks
