### ISSUE TITLE
Need extra imports `uvicorn`, `ssl`, `starlette` for result of `marimo export html-wasm` to work

### ISSUE THREAD

**Issue by cmarqu** [marimo-team/marimo#3210]
### Describe the bug

I found that when doing a `marimo export html-wasm ...` on a notebook that uses numpy and matplotlib to draw a simple graph, I needed the following extra imports in the notebook: `uvicorn`, `ssl`, `starlette` to be able to use the output, otherwise I'd get the following traceback:
```
Traceback (most recent call last):
  File "/lib/python3.12/site-packages/marimo/_runtime/executor.py", line 158, in execute_cell
    return eval(cell.last_expr, glbls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Cell marimo://notebook.py#cell=cell-1
, line 108, in <module>
    mo.mpl.interactive(plt.gcf())
  File "/lib/python3.12/site-packages/marimo/_plugins/stateless/mpl/_mpl.py", line 365, in interactive
    app = get_or_create_application()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/marimo/_plugins/stateless/mpl/_mpl.py", line 270, in get_or_create_application
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'
```

When adding the mentioned imports to my notebook, the exported WASM works.

### Environment

```
$ marimo env
{
  "marimo": "0.10.4",
  "OS": "Linux",
  "OS Version": "3.10.0-1160.118.1.el7.x86_64",
  "Processor": "x86_64",
  "Python Version": "3.11.4",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.18.4",
    "packaging": "24.2",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "ruff": "0.8.3",
    "starlette": "0.42.0",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.34.0",
    "websockets": "14.1"
  },
  "Optional Dependencies": {}
}
```

### Code to reproduce

I can't directly share the code, but the notebook ends with the line `mo.mpl.interactive(plt.gcf())` in case it matters.

**Comment by mscolnick** [comment]
Yes unfortunately not all python code is compatible with wasm, and `mo.mpl.interactive(` is one of them. so its not supported now, but i can at least have a warning instead of failing

**Comment by mscolnick** [comment]
Going to close with #3212 which just falls back to normal matplotlib (non-interactive)

For now we can't do much to support it (as far as i know)
