### ISSUE TITLE
Dataframe view crashes after `pd.set_option('display.max_rows', None)`

### ISSUE THREAD

**Issue by kevin-hanselman** [marimo-team/marimo#598]
### Describe the bug

It appears that marimo is expecting Pandas' `display.max_rows` to be an integer, but Pandas allows it to be `None`. Here's the exception traceback:

```
Traceback (most recent call last):
  File ".../.venv/lib/python3.11/site-packages/marimo/_output/formatting.py", line 123, in try_format
    mimetype, data = formatter(obj)
                     ^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.11/site-packages/marimo/_output/formatters/pandas_formatters.py", line 31, in _show_dataframe
    len(df.index) > max_rows or len(df.columns) > max_columns
    ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

As a side note, it would be nice for marimo to support the `pd.option_context` context manager for scoped options. I'm sure the marimo team can appreciate avoiding global state. 😄  

### Environment

``` json
{
  "marimo": "0.1.78",
  "OS": "Linux",
  "OS Version": "5.15.107+",
  "Processor": "x86_64",
  "Python Version": "3.11.6",
  "Binaries": {
    "Chrome": "--",
    "Node": "v20.8.1"
  },
  "Requirements": {
    "black": "23.12.1",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "tomlkit": "0.12.3",
    "tornado": "6.4",
    "typing_extensions": "4.9.0"
  }
}
```

### Code to reproduce

``` python
import marimo

__generated_with = "0.1.78"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    import pandas as pd
    return mo, pd


@app.cell
def __(pd):
    n_rows = 100
    foo = pd.DataFrame(
        {'a': range(0, n_rows), 'b': range(0, n_rows * 2, 2)}
    )
    foo
    return foo, n_rows


@app.cell
def __(foo, pd):
    pd.set_option('display.max_rows', None)
    # crashes here
    foo
    return


if __name__ == "__main__":
    app.run()
```

**Comment by mscolnick** [comment]
@kevin-hanselman , we fixed bug (it will be in the next release).

> As a side note, it would be nice for marimo to support the pd.option_context context manager for scoped options. I'm sure the marimo team can appreciate avoiding global state. 😄

For your second question, you can do something like this:

```python
n_rows = 100
foo = pd.DataFrame(
    {'a': range(0, n_rows), 'b': range(0, n_rows * 2, 2)}
)
foo
with pd.option_context('display.max_rows', 2):
    mo.output.replace(foo)
```
