### ISSUE TITLE
Working code on editor crashes when launching via python 

### ISSUE THREAD

**Issue by eracle** [marimo-team/marimo#599]
### Describe the bug

```
root@be8b9311b1a7:/app/project/# python /app/project/notebooks/test.py 

Traceback (most recent call last):
  File "/app/project/notebooks/test.py", line 166, in <module>
    app.run()
  File "/usr/local/lib/python3.9/site-packages/marimo/_ast/app.py", line 300, in run
    {name: glbls[name] for name in self._defs},
  File "/usr/local/lib/python3.9/site-packages/marimo/_ast/app.py", line 300, in <dictcomp>
    {name: glbls[name] for name in self._defs},
KeyError: 'obj'
```

### Environment

```
{
  "marimo": "0.1.78",
  "OS": "Linux",
  "OS Version": "5.15.0-91-generic",
  "Processor": "",
  "Python Version": "3.9.18",
  "Binaries": {
    "Chrome": "--",
    "Node": "--"
  },
  "Requirements": {
    "black": "23.11.0",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "tomlkit": "0.12.3",
    "tornado": "6.4",
    "typing_extensions": "4.9.0"
  }
}



```

### Code to reproduce

```
import marimo

__generated_with = "0.1.78"
app = marimo.App(width="full")


@app.cell
def __():
    objects =  iter([])

    # Wrap the queryset with tqdm for a progress bar
    for obj in objects:
        pass
    return (
        obj,
        objects,
    )


if __name__ == "__main__":
    app.run()

**Comment by akshayka** [comment]
Thanks for reporting! I will take a look.

**Comment by akshayka** [comment]
I was unable to run your code; got a Django error, even when I put it in a plain vanilla Python script. Can you give me a minimal repro on how to configure my environment? I don't have experience with Django.

```
Traceback (most recent call last):
  Cell <cell-0>, line 1
    from django.contrib.sessions.models import Session
  File /home/akshay/envs/playground/lib/python3.10/site-packages/django/contrib/sessions/models.py, line 1
    from django.contrib.sessions.base_session import AbstractBaseSession, BaseSessionManager
  File /home/akshay/envs/playground/lib/python3.10/site-packages/django/contrib/sessions/base_session.py, line 26
    class AbstractBaseSession(models.Model):
  File /home/akshay/envs/playground/lib/python3.10/site-packages/django/db/models/base.py, line 129, in __new__
    app_config = apps.get_containing_app_config(module)
  File /home/akshay/envs/playground/lib/python3.10/site-packages/django/apps/registry.py, line 260, in get_containing_app_config
    self.check_apps_ready()
  File /home/akshay/envs/playground/lib/python3.10/site-packages/django/apps/registry.py, line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File /home/akshay/envs/playground/lib/python3.10/site-packages/django/conf/__init__.py, line 102, in __getattr__
    self._setup(name)
  File /home/akshay/envs/playground/lib/python3.10/site-packages/django/conf/__init__.py, line 82, in _setup
    raise ImproperlyConfigured(
ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by eracle** [comment]
Thanks to Chatgpt I was able to mockit, now it should work without setting up django config files.

**Comment by akshayka** [comment]
Thank you! You've correctly diagnosed the issue. I'll have a fix up momentarily.

**Comment by eracle** [comment]
Thank you. Looking forward to have it on the next release.
