### ISSUE TITLE
Crash when interacting with linked UI elements

### ISSUE THREAD

**Issue by kevin-hanselman** [marimo-team/marimo#641]
### Describe the bug

I'm trying to link (a.k.a. tie) two UI elements, following the [Reactive state guide](https://docs.marimo.io/guides/state.html#example-tied-elements). Specifically, I'd like to implement a "reset to default(s)" button. See my code below for a minimally reproducible example. Interacting with the input (in this example, a slider) works fine, but I see this error as soon as I click the reset button:

```
Exception in thread Thread-1 (launch_kernel_with_cleanup):
Traceback (most recent call last):
    File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
        self.run()
    File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
        self._target(*self._args, **self._kwargs)
    File ".../.venv/lib/python3.11/site-packages/marimo/_server/sessions.py", line 114, in launch_kernel_with_cleanup
        runtime.launch_kernel(*args)
    File ".../.venv/lib/python3.11/site-packages/marimo/_runtime/runtime.py", line 1156, in launch_kernel
        kernel.set_ui_element_value(request)
    File ".../.venv/lib/python3.11/site-packages/marimo/_runtime/runtime.py", line 912, in set_ui_element_value
        - self.graph.definitions[name]
            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: '_cell_1_reset'
```

Additionally, once the error is thrown, marimo crashes. The marimo web app reports "kernel not found", but the marimo CLI continues to run. Ideally marimo would recover from a crash, perhaps by restarting the kernel?

### Environment

```
{
  "marimo": "0.1.81",
  "OS": "Darwin",
  "OS Version": "23.2.0",
  "Processor": "arm",
  "Python Version": "3.11.7",
  "Binaries": {
    "Chrome": "120.0.6099.234",
    "Node": "v21.6.0"
  },
  "Requirements": {
    "black": "23.12.1",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "tomlkit": "0.12.3",
    "tornado": "6.4",
    "typing_extensions": "4.9.0"
  }
}
```

### Code to reproduce

```
import marimo
 
__generated_with = "0.1.81"
app = marimo.App()
 
 
@app.cell
def __():
        import marimo as mo
        return mo,
 
 
@app.cell
def __(mo):
        _default_box_size = 500
        get_box_size, set_box_size = mo.state(_default_box_size)
        box_size = mo.ui.slider(
                label="Width:",
                start=200,
                stop=1000,
                value=get_box_size(),
                on_change=set_box_size,
        )
        _reset = mo.ui.button(
                label="Reset to default",
                on_click=lambda _: set_box_size(_default_box_size),
        )
        mo.hstack([box_size, _reset], justify="start", gap=1)
        return box_size, get_box_size, set_box_size
 
 
@app.cell
def __(box_size, mo):
        _size = box_size.value
 
        # Adapted from: marimo/examples/layout.py
        mo.Html(
                f"""
                <div style='
                        width: {_size}px;
                        height: {_size}px;
                        background-color: orange;
                '>
                """
        )
        return
 
 
if __name__ == "__main__":
        app.run()
```

**Comment by mscolnick** [comment]
the crashing is definitely a bug. but your state won't update in the current form you have it. can you move your state to a different cell?

```python
    # these lines should be in there own cell
    _default_box_size = 500
    get_box_size, set_box_size = mo.state(_default_box_size)
```

**Comment by akshayka** [comment]
Hey @kevin-hanselman , I've copied code below that should work. The change required splitting up the cells and renaming `_reset` to `reset`.

- When a state setter is called, all _other_ cells that refer to its getter are run (in particular the cell that called the setter is not re-run). That's why the cells must be split up. More info here: https://docs.marimo.io/guides/state.html#updating-state
- UI elements only work if they are assigned to global variables; by prefixing `reset` with an underscore, it became local to the cell, and that surfaced a bug in marimo causing it to crash. We'll definitely fix that -- thanks for bringing it to our attention.

```python
import marimo

__generated_with = "0.1.78"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    return mo,


@app.cell
def __(mo):
    default_box_size = 500
    get_box_size, set_box_size = mo.state(default_box_size)
    return default_box_size, get_box_size, set_box_size


@app.cell
def __(get_box_size, mo, set_box_size):
    box_size = mo.ui.slider(
        label="Width:",
        start=200,
        stop=1000,
        value=get_box_size(),
        on_change=set_box_size,
    )
    return box_size,


@app.cell
def __(box_size, default_box_size, mo, set_box_size):
    reset = mo.ui.button(
        label="Reset to default",
        on_click=lambda _: set_box_size(default_box_size),
    )
    mo.hstack([box_size, reset], justify="start", gap=1)
    return reset,


@app.cell
def __(box_size, mo):
    _size = box_size.value

    # Adapted from: marimo/examples/layout.py
    mo.Html(
        f"""
                <div style='
                        width: {_size}px;
                        height: {_size}px;
                        background-color: orange;
                '>
                """
    )
    return


if __name__ == "__main__":
    app.run()
```
