### ISSUE TITLE
KeyError in mo.ui.text, while typing

### ISSUE THREAD

**Issue by SpielerNogard** [marimo-team/marimo#746]
### Describe the bug

I have the following three cells

```python
get_action_site, set_action_site = mo.state([])
```

```python
def _action_site_creator(selection:str):
    if selection == 'new_api_path':
        test_api_path_text = mo.md('Please input the API path you want to add')
        input_api_path = mo.ui.text(placeholder='/location', value="")
        # add 
        set_action_site([test_api_path_text, input_api_path])
    else:
        set_action_site([])
text_button = mo.md('#### Select the action you want to do')
button = mo.ui.radio(options={'Add a new API path':'new_api_path',
                              'Add a new frontend route':'TEST',
                              'Create a new role for portfolio':'TEST',
                              'Give a user a role in portfolio':'TEST',
                              'Get all roles with permission for path':'TEST',
                              'Add a new frontend panel':'TEST',}, inline=False, on_change=_action_site_creator)
mo.vstack([text_button, button], align="stretch", gap=0.25)
```

```python
mo.vstack([*get_action_site()])
```

I want whenever an action is selected in the radiobutton, to change the items in the third cell.
This works fine, but if i start to type in the text field a KeyError occurres
on every keypress the error occurres again, but with a new key

```
An exception was raised by a UIElement's on_change handler:
Traceback (most recent call last):
  File "/Users/christophermuller/Documents/Repositories/Notebooks/.venv/lib/python3.8/site-packages/marimo/_runtime/runtime.py", line 904, in set_ui_element_value
    component._update(value)
  File "/Users/christophermuller/Documents/Repositories/Notebooks/.venv/lib/python3.8/site-packages/marimo/_plugins/ui/_core/ui_element.py", line 378, in _update
    self._value = self._convert_value(value)
  File "/Users/christophermuller/Documents/Repositories/Notebooks/.venv/lib/python3.8/site-packages/marimo/_plugins/ui/_impl/input.py", line 313, in _convert_value
    return self.options[value] if value is not None else None
KeyError: 't'
```

### Environment

{
  "marimo": "0.2.1",
  "OS": "Darwin",
  "OS Version": "23.2.0",
  "Processor": "arm",
  "Python Version": "3.8.18",
  "Binaries": {
    "Chrome": "121.0.6167.139",
    "Node": "v21.6.1"
  },
  "Requirements": {
    "black": "24.1.1",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "starlette": "0.37.0",
    "tomlkit": "0.12.3",
    "typing_extensions": "4.9.0",
    "uvicorn": "0.27.0.post1"
  }
}

### Code to reproduce

```python
import marimo as mo
from typing import List, Dict
import datetime
```

```python
get_action_site, set_action_site = mo.state([])
```

```python
def _action_site_creator(selection:str):
    if selection == 'new_api_path':
        test_api_path_text = mo.md('Please input the API path you want to add')
        input_api_path = mo.ui.text(placeholder='/location', value="")
        # add 
        set_action_site([test_api_path_text, input_api_path])
    else:
        set_action_site([])
text_button = mo.md('#### Select the action you want to do')
button = mo.ui.radio(options={'Add a new API path':'new_api_path',
                              'Add a new frontend route':'TEST',
                              'Create a new role for portfolio':'TEST',
                              'Give a user a role in portfolio':'TEST',
                              'Get all roles with permission for path':'TEST',
                              'Add a new frontend panel':'TEST',}, inline=False, on_change=_action_site_creator)
mo.vstack([text_button, button], align="stretch", gap=0.25)
```

```python
mo.vstack([*get_action_site()])
```

**Comment by SpielerNogard** [comment]
jo, this should work, thanks for the code snippet

**Comment by mscolnick** [comment]
Going to close this issue - please re-open if you hit any related issue
