### ISSUE TITLE
run --watch fails if directory changed, suggested fix included

### ISSUE THREAD

**Issue by alefminus** [marimo-team/marimo#773]
### Describe the bug

Trying the reproducer results in the following failure due to a changed working directory meaning the Session.filename is not present:

```
✦ at 16:10:27 ❯ marimo run --watch watch_fail_after_chdir.py
[W 240212 16:10:28 file_watcher:21] watchdog is not installed, using polling file watcher

        Running watch_fail_after_chdir.py ⚡

        URL: http://localhost:2722

Task exception was never retrieved
future: <Task finished name='Task-3' coro=<PollingFileWatcher._poll() done, defined at /venv/lib/python3.12/site-packages/marimo/_utils/file_watcher.py:68> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/marimo/_utils/file_watcher.py", line 80, in _poll
    await self.on_file_changed()
  File "/venv/lib/python3.12/site-packages/marimo/_utils/file_watcher.py", line 36, in on_file_changed
    await self.callback(self.path)
  File "/venv/lib/python3.12/site-packages/marimo/_server/sessions.py", line 572, in on_file_changed
    session.app = self.load_app()
                  ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/marimo/_server/sessions.py", line 405, in load_app
    app = codegen.get_app(self.filename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/marimo/_ast/codegen.py", line 204, in get_app
    with open(filename, "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'watch_fail_after_chdir.py'
```

### Environment

Fedora 39, python 3.12, marimo 0.2.4

### Code to reproduce

```
import marimo

__generated_with = "0.2.4"
app = marimo.App(width="full")


@app.cell
def __():
    from pathlib import Path
    import marimo as mo
    import os

    os.chdir('/tmp')
    a = 12
    return (
            a
    )


if __name__ == "__main__":
    app.run()
```

# Proposed fix

This fixes the issue for me
```diff
diff --git a/marimo/_server/sessions.py b/marimo/_server/sessions.py
index 2a435e6..529bc1f 100644
--- a/marimo/_server/sessions.py
+++ b/marimo/_server/sessions.py
@@ -369,6 +369,7 @@ class SessionManager:
         lsp_server: LspServer,
     ) -> None:
         self.filename = filename
+        self.path = Path(filename).absolute() if filename is not None and Path(filename).exists() else None
         self.mode = mode
         self.development_mode = development_mode
         self.quiet = quiet
@@ -401,7 +402,7 @@ class SessionManager:
         Load the app from the current file.
         Otherwise, return an empty app.
         """
-        app = codegen.get_app(self.filename)
+        app = codegen.get_app(self.path)
         if app is None:
             empty_app = InternalApp(App())
             empty_app.cell_manager.register_cell(
```

I added the "exists" because the signature for filename is Optional[str], so I assumed there are some uses
for passing in None.

**Comment by mscolnick** [comment]
thanks for identifying the issue and fix - I will create a PR for this today
