### ISSUE TITLE
Export Marimo notebook to PDF

### ISSUE THREAD

**Issue by scls19fr** [marimo-team/marimo#896]
### Description

Hello,

I think PDF export is missing

Kind regards

### Suggested solution

Following #892 a PDF export feature will be great.
It will be even greater if it is accessible both through CLI and from UI
Embedding code into PDF to me able to regenerate notebook (into https://marimo.app/ or in our own Marimo install) could be a nice feature to also have.

**Comment by akshayka** [comment]
Thanks for the feature request! It's one we've gotten several times now, so it's definitely in our backlog.

**Comment by mscolnick** [comment]
@scls19fr are there any pdf rendering libraries you recommend?

Exporting to PDF by CLI will be tricky. It'll still require a browser. Do you expect that to run a headless browser? Where do you want to run this CLI command?

**Comment by scls19fr** [comment]
Yes headless CLI command will be fine.

Maybe fpdf2 https://py-pdf.github.io/fpdf2/

Or

Reportlab https://docs.reportlab.com/

Or for low level pdf generation

pydyf https://www.courtbouillon.org/pydyf/

See 
https://akpolatcem.medium.com/creating-various-pdf-files-via-python-eba91a40df9d

**Comment by scls19fr** [comment]
This SO question can help https://stackoverflow.com/questions/27649600/python-html-to-pdf-with-full-support-for-css3-and-html5 about rendering html/css to pdf.

**Comment by fujimuramasa** [comment]
It would be better if native pdf export could provide choice disabling some cells like slider or dropdown.

**Comment by mscolnick** [comment]
@scls19fr @fujimuramasa 
We have a way to HTML export now from the CLI: `marimo export html notebook.py -o notebook.html`. Could you pipe this into one of those other CLI/tools to convert it to a PDF? Not sure if our html -> pdf looks clunky (would likely need a browser to render it well)

**Comment by scls19fr** [comment]
Hi @mscolnick ,

Sorry for not answering quickly I was quite busy.

export html seems to be broken in my install.

```
> marimo export html am_modulation.py -o am_modulation.html
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\scelles\anaconda3\Scripts\marimo.exe\__main__.py", line 7, in <module>
  File "C:\Users\scelles\anaconda3\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\scelles\anaconda3\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\scelles\anaconda3\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\scelles\anaconda3\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\scelles\anaconda3\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\scelles\anaconda3\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\scelles\anaconda3\Lib\site-packages\marimo\_cli\export\commands.py", line 97, in html
    (html, _filename) = asyncio.run(
                        ^^^^^^^^^^^^
  File "C:\Users\scelles\anaconda3\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\scelles\anaconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\scelles\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\scelles\anaconda3\Lib\site-packages\marimo\_server\export\utils.py", line 43, in run_app_then_export_as_html
    session = await run_app_until_completion(file_manager, cli_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\scelles\anaconda3\Lib\site-packages\marimo\_server\export\utils.py", line 92, in run_app_until_completion
    session = Session.create(
              ^^^^^^^^^^^^^^^
  File "C:\Users\scelles\anaconda3\Lib\site-packages\marimo\_server\sessions.py", line 290, in create
    return cls(
           ^^^^
  File "C:\Users\scelles\anaconda3\Lib\site-packages\marimo\_server\sessions.py", line 330, in __init__
    self.message_distributor.start()
  File "C:\Users\scelles\anaconda3\Lib\site-packages\marimo\_utils\distributor.py", line 54, in start
    asyncio.get_event_loop().add_reader(
  File "C:\Users\scelles\anaconda3\Lib\asyncio\events.py", line 530, in add_reader
    raise NotImplementedError
NotImplementedError
(base) C:\.....\marimo [main ≡ +1 ~0 -0 !]> marimo --version
0.4.5
```

**Comment by mscolnick** [comment]
This might be an issue with windows (or the python version) - @scls19fr can you create a different issue with your python version and env info (with `marimo env`)

**Comment by scls19fr** [comment]
```
marimo env
{
  "marimo": "0.4.5",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 142 Stepping 12, GenuineIntel",
  "Python Version": "3.11.5",
  "Binaries": {
    "Browser": "124.0.6367.91",
    "Node": "v22.0.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.18.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8",
    "pygments": "2.15.1",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.7.1",
    "black": "0.0"
  }
}
```

**Comment by roaldarbol** [comment]
Could it make sense to consider making a `pandoc` reader/writer? That would enable not just PDF export (through both LaTeX/Typst which would also allow use of many templates for customised PDFs), but endless other conversion opportunities. It seems that the readers/writers need to be written in Lua, but I'm not quite sure whether that is the case (https://pandoc.org/custom-readers.html).

**Comment by dmadisetti** [comment]
Here's an example of a PDF with marimo: https://dmadisetti.github.io/quarto-marimo/tutorials/example-pdf.pdf

Using a pandoc filter (and quarto, but you can remove the quarot bit). I think now that marimo can interpret markdown, I can rewrite the filter to be less convoluted

**Comment by scls19fr** [comment]
I saw #2387 is disabling PDF export while editing. I think we should have 2 kind of PDF exports.
- PDF export while simply viewing which could simply provide viewable elements
- PDF export while editing could provide a PDF file containing all viewable elements but also a banner like HTML export to "This is a static Python notebook built using [marimo](https://github.com/marimo-team/marimo).
Some interactive features may not work, see ways to run or edit this."

**Comment by s-celles** [comment]
Thanks @mscolnick @akshayka and @peter-gy
