### ISSUE TITLE
RecursionError when using AnyWidget

### ISSUE THREAD

**Issue by mludv** [marimo-team/marimo#930]
### Describe the bug

Running the AnyWidget example will break the server when using run mode `marimo run ...`

I've created a notebook with two cells, one displaying the widget and one displaying the value. When running in read mode it works initially, but refresh the page (forcing cleanup) the server dies.

```
marimo run counter_test.py

        Running counter_test.py ⚡

        URL: http://localhost:2719

Exception in thread Thread-3 (launch_kernel_with_cleanup):
Traceback (most recent call last):
  File "/home/max/code/trading_analysis/.venv/lib/python3.10/site-packages/pdb.py", line 169, in __init__
    super(Pdb, self).__init__(*args, **kwargs)
  File "/home/max/code/trading_analysis/.venv/lib/python3.10/site-packages/pdb.py", line 169, in __init__
    super(Pdb, self).__init__(*args, **kwargs)
  File "/home/max/code/trading_analysis/.venv/lib/python3.10/site-packages/pdb.py", line 169, in __init__
    super(Pdb, self).__init__(*args, **kwargs)
  [Previous line repeated 991 more times]
  File "/home/max/code/trading_analysis/.venv/lib/python3.10/site-packages/pdb.py", line 163, in __init__
    self.config = self.get_config(self.ConfigFactory)
  File "/home/max/code/trading_analysis/.venv/lib/python3.10/site-packages/fancycompleter.py", line 197, in get_config
    rcfile = os.path.normpath(os.path.expanduser(filename))
  File "/usr/lib/python3.10/posixpath.py", line 244, in expanduser
    if 'HOME' not in os.environ:
  File "/usr/lib/python3.10/_collections_abc.py", line 830, in __contains__
    self[key]
  File "/usr/lib/python3.10/os.py", line 677, in __getitem__
    value = self._data[self.encodekey(key)]
  File "/usr/lib/python3.10/os.py", line 756, in encode
    if not isinstance(value, str):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Environment

```json
{
  "marimo": "0.3.1",
  "OS": "Linux",
  "OS Version": "5.15.90.1-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Chrome": "--",
    "Node": "v20.11.1"
  },
  "Requirements": {
    "black": "24.2.0",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7.1",
    "starlette": "0.27.0",
    "tomlkit": "0.12.4",
    "typing_extensions": "4.8.0",
    "uvicorn": "0.26.0"
  }
}
```

### Code to reproduce

```python
import marimo

__generated_with = "0.3.1"
app = marimo.App()


@app.cell
def __():
    import anywidget
    import traitlets
    import marimo as mo

    class CounterWidget(anywidget.AnyWidget):
      # Widget front-end JavaScript code
      _esm = """
        function render({ model, el }) {
          let getCount = () => model.get("count");
          let button = document.createElement("button");
          button.innerHTML = `count is ${getCount()}`;
          button.addEventListener("click", () => {
            model.set("count", getCount() + 1);
            model.save_changes();
          });
          model.on("change:count", () => {
            button.innerHTML = `count is ${getCount()}`;
          });
          el.appendChild(button);
        }
        export default { render };
      """
      _css = """
        button {
          padding: 5px !important;
          border-radius: 5px !important;
          background-color: #f0f0f0 !important;

          &:hover {
            background-color: lightblue !important;
            color: white !important;
          }
        }
      """

      # Stateful property that can be accessed by JavaScript & Python
      count = traitlets.Int(0).tag(sync=True)

    widget = mo.ui.anywidget(CounterWidget())

    widget
    return CounterWidget, anywidget, mo, traitlets, widget


@app.cell
def __(widget):
    widget.value
    return


if __name__ == "__main__":
    app.run()
```

**Comment by akshayka** [comment]
@mludv , thanks for reporting.

Unfortunately I'm unable to reproduce this on my machine, but I can walk through the issue with you, and hopefully we can arrive at a fix.

What's curious is that the stack trace points to `Pdb` ... there is likely a clue for me to follow there. In the meantime, could you answer a couple questions?

- Is this issue specific to `marimo run`, or do you see it in `marimo edit` too?
- Do you see the same error when refreshing the following notebook, after starting it with `marimo run`?
```python
import marimo

__generated_with = "0.3.1"
app = marimo.App()


@app.cell
def __():
    print('hello world')
    return


if __name__ == "__main__":
    app.run()
```

**Comment by mludv** [comment]
@akshayka That solves the issue on my side, thank you!
